spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:basicspringmvcapp
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
